Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 22, in main
    loader = data.Data(args)
  File "/usr/itetnas04/data-scratch-01/dlim_01hs20/data/EDSR-PyTorch/src/data/__init__.py", line 24, in __init__
    datasets.append(getattr(m, module_name)(args, name=d))
  File "/usr/itetnas04/data-scratch-01/dlim_01hs20/data/EDSR-PyTorch/src/data/div2k.py", line 16, in __init__
    super(DIV2K, self).__init__(
  File "/usr/itetnas04/data-scratch-01/dlim_01hs20/data/EDSR-PyTorch/src/data/srdata.py", line 28, in __init__
    os.makedirs(path_bin, exist_ok=True)
  File "/usr/itetnas04/data-scratch-01/dlim_01hs20/data/conda_envs/DLIM_project/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/itetnas04/data-scratch-01/dlim_01hs20/data/conda_envs/DLIM_project/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/itetnas04/data-scratch-01/dlim_01hs20/data/conda_envs/DLIM_project/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '../../../zoomdata'
